name: Practica GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias (si las tuvieras)
        run: pip install -r requirements.txt || echo "No requirements.txt"

      - name: Ejecutar tests
        run: python -m unittest test_suma.py > test_log.txt

      - name: Subir log como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: test_log.txt
